# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180228_2143'),
        ('sweet', '0002_auto_20180209_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_cost', models.IntegerField(default=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweet.Category')),
                ('operator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweet.Operator')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='operator_id',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterIndexTogether(
            name='order',
            index_together=set([('id', 'slug')]),
        ),
    ]
