# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0003_auto_20180228_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default='Stuff'),
            preserve_default=False,
        ),
    ]
