# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0004_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
