# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0006_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='domain',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('D', 'DryCleaner'), ('T', 'Tailor')], default='D', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='operator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweet.Profile'),
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
